//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassifiedAds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdDetail
    {
        public int AdId { get; set; }
        public string AdTitle { get; set; }
        public string AdType { get; set; }
        public string Status { get; set; }
        public string Price { get; set; }
        public string Quantity { get; set; }
        public string Image_path { get; set; }
        public Nullable<int> User_Id { get; set; }
    }
}
